import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "@/style/pretendard.css";
import "@/style/global.css";
import { Analytics } from '@vercel/analytics/react';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link rel="icon" href="/favicon.ico" title="icon" />
        <meta name="color-scheme" content="light dark" />
        <meta name="supported-color-schemes" content="dark" />
      </head>
      <body>
        {/* <Header /> */}
        <main className="min-h-screen flex flex-col">
          <div className="">
            {children}
          </div>
					{/* <Footer /> */}
        </main>
        {/* Vercel 측정도구 */}
        <Analytics />
      </body>
    </html>
  );
}
